### ISSUE TITLE
检查最小单位, 可以是文件的新增/修改部分吗

### ISSUE THREAD

**Issue by ukyo6** [Western-parotia/EaseLint#4]
你好:
现在的检查范围好像是diff后的文件, 能缩小到文件里的新增/修改部分吗
因为整个文件里可能有历史的lint问题

**Comment by juziml** [comment]
扫描都是基于文件的，所以默认无法支持到代码块级别。比如IDEA里面也无法按代码块做忽略吧。
但是有个办法你可以尝试，就是将修改的代码块 diff出来后写入一个临时的代码文件给lint去扫描。这个临时文件可以放在临时目录里，扫描完删除。不过扫描输出的报告你可能要修改下，做个区分。
